version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: test_teddy
    restart: unless-stopped
    environment:
      POSTGRES_USER: teddy_user
      POSTGRES_PASSWORD: teddy_password
      POSTGRES_DB: teddy_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
